# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RTEAIGCServiceDemo' do
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
  
  pod 'RTMTokenBuilder', "1.0.2"
  pod 'AgoraAudio_Special_iOS', '4.2.6.8'
  pod 'AgoraComponetLog'
  pod 'MicrosoftCognitiveServicesSpeech-iOS', '1.25'
  pod 'SocketRocket', '0.7.0'
end
